export interface MovieData{
    Title : string
    Year : number
    Rated : string
    Released : Date
    Runtime : string
    Genre : string
    Director : string
    Writer : string
    Actors : string
    Plot : string
    Language : string
    Country : string
    Poster : string
    Metascore : number
    Rating : number
    Votes : string
    ID : string
    Type : string
    Price : number
}